# Generated by Django 3.2.12 on 2022-05-21 16:14

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20220320_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingresource',
            old_name='accommodation_length',
            new_name='how_long',
        ),
        migrations.RenameField(
            model_name='housingresource',
            old_name='people_to_accommodate',
            new_name='how_many_people',
        ),
        migrations.RenameField(
            model_name='housingresource',
            old_name='people_to_accommodate_raw',
            new_name='people_desc',
        ),
        migrations.RenameField(
            model_name='housingresource',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='housingresource',
            old_name='when_to_call',
            new_name='phone_when',
        ),
        migrations.RenameField(
            model_name='housingresource',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='about_info',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='age',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='backup_phone_number',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='can_take_person_with_pets',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='city_and_zip_code',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='email',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='living_with_pets',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='note',
        ),
        migrations.RemoveField(
            model_name='housingresource',
            name='will_pick_up_now',
        ),
        migrations.AddField(
            model_name='housingresource',
            name='can_live_with_pets',
            field=models.BooleanField(default=False, verbose_name='Can you live with pets?'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='city',
            field=models.CharField(default='', max_length=30, verbose_name='City and zip code'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When can you start providing the accommodation?', verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='description',
            field=models.TextField(blank=True, default='', help_text="who do you live with (if you'll host at your place)?, some rules about place? ", max_length=2048, verbose_name='Something about accommodation'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='disable',
            field=models.BooleanField(default=False, verbose_name='Facilities for the disabled'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='food',
            field=models.BooleanField(default=False, verbose_name='Do you provide food?'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='job',
            field=models.BooleanField(default=False, verbose_name='Do you offer a job'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='job_descr',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Transport'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='pets',
            field=models.BooleanField(default=False, verbose_name='Do you live with pets?'),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='transport_desc',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='Transport'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='details',
            field=models.TextField(blank=True, default='', help_text='A bunch of information about the place - presence of animals, languages spoken by tenants, availability of bed linen and towels, others', max_length=2048, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='resource',
            field=models.CharField(choices=[('house', 'House'), ('flat', 'Apartment'), ('room', 'Room'), ('sofa', 'Sofat')], max_length=1024, verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='transport',
            field=models.BooleanField(default=False, verbose_name='Do you offer transport'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='content_primary_language',
            field=markdownx.models.MarkdownxField(help_text="You can use <a href='https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax' target='_blank'>Markdown</a> here.", verbose_name='Content in the primary language'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='content_secondary_language',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text="You can use <a href='https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax' target='_blank'>Markdown</a> here.", verbose_name='Content in the secondary language'),
        ),
    ]
