# Generated by Django 3.2.12 on 2022-05-21 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20220521_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='when',
            new_name='how_long_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='can_stay_with_pets',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='how_long',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='people',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='transport_needed',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='traveling_with_pets',
        ),
        migrations.AddField(
            model_name='submission',
            name='can_pay',
            field=models.BooleanField(default=False, verbose_name='Is the payment possible?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='can_pay_pln',
            field=models.FloatField(blank=True, default=0, max_length=128, verbose_name='Monthly payment in PLN'),
        ),
        migrations.AddField(
            model_name='submission',
            name='car',
            field=models.BooleanField(default=True, verbose_name='Do you have a car?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='children',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='Children age'),
        ),
        migrations.AddField(
            model_name='submission',
            name='cigarettes',
            field=models.BooleanField(default=False, verbose_name='Does anyone smokes cigarettes?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='city_of_origin',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='City of your origin'),
        ),
        migrations.AddField(
            model_name='submission',
            name='disable',
            field=models.BooleanField(default=False, help_text='Anyone with a disability or chronic diseases', verbose_name='Disabilities'),
        ),
        migrations.AddField(
            model_name='submission',
            name='disable_desc',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='Kind of disability'),
        ),
        migrations.AddField(
            model_name='submission',
            name='how_long_desc',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='submission',
            name='how_long_infinite',
            field=models.BooleanField(default=False, verbose_name='Without ending date'),
        ),
        migrations.AddField(
            model_name='submission',
            name='how_long_months',
            field=models.IntegerField(blank=True, default=0, verbose_name='How many months?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='job_desc',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='In what kind of job are you interested in?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='job_needed',
            field=models.BooleanField(default=False, verbose_name='Do you want to work?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='languages_en',
            field=models.BooleanField(default=False, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='submission',
            name='languages_others',
            field=models.CharField(blank=True, help_text='Other languages that the person speaks besides Polish, Ukrainian and Russian', max_length=1024, null=True, verbose_name='Other languages'),
        ),
        migrations.AddField(
            model_name='submission',
            name='languages_pl',
            field=models.BooleanField(default=False, verbose_name='Polish'),
        ),
        migrations.AddField(
            model_name='submission',
            name='languages_ru',
            field=models.BooleanField(default=False, verbose_name='Russian'),
        ),
        migrations.AddField(
            model_name='submission',
            name='men',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='Men age'),
        ),
        migrations.AddField(
            model_name='submission',
            name='people_nb',
            field=models.IntegerField(default=1, verbose_name='The number of people'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pesel',
            field=models.BooleanField(default=True, verbose_name='Do you have polish pesel?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pet',
            field=models.BooleanField(default=False, verbose_name='Pets'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pet_alergic',
            field=models.BooleanField(default=False, verbose_name='Animal allergies'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pet_desc',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='What kind of animal'),
        ),
        migrations.AddField(
            model_name='submission',
            name='phone_number_pl',
            field=models.CharField(default='', max_length=128, verbose_name='Polish phone number'),
        ),
        migrations.AddField(
            model_name='submission',
            name='phone_number_ukr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ukrainian phone number'),
        ),
        migrations.AddField(
            model_name='submission',
            name='preferred_city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Preferred city'),
        ),
        migrations.AddField(
            model_name='submission',
            name='preferred_country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Preferred country'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pregnant',
            field=models.BooleanField(default=False, verbose_name='Pregnant'),
        ),
        migrations.AddField(
            model_name='submission',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Registration date'),
        ),
        migrations.AddField(
            model_name='submission',
            name='stamps',
            field=models.BooleanField(default=True, verbose_name='Do you have polish border stamps?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='women',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='Women age'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When can you start providing the accommodation?', verbose_name='Registration date'),
        ),
    ]
